language: node_js
node_js:
- '6.9.3'
addons:
  ssh_known_hosts:
  - new.sdh.or.id
  - 139.59.216.194
before_install:
- bash _travis/install.sh
script:
- bash _travis/build.sh
after_success:
- bash _travis/deploy.sh
notifications:
  webhooks: https://hooks.zapier.com/hooks/catch/1969538/hin54e/
